### ISSUE TITLE
Class na respawn Santy

### ISSUE THREAD

**Issue by Morcinus** [Morcinus/Santa-Game#5]
- [x] resetovani sceny pri umreni
- [x] zakladni animace prechodu ze sceny + napis neco jako game over (Opravit, aby nebyl videt joystick)
- [x] funkce ktera se da zavolat kdyz santa umre

**Comment by riskin88** [comment]
+ se to samy musi udelat kdyz uz nebude zbyvat cas
a naopak Victory message kdyz se pocet zbyvajicich darku == 0
